# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common_service.proto',
  package='rasnet.service',
  syntax='proto3',
  serialized_options=_b('\n\033org.rasdaman.rasnet.service'),
  serialized_pb=_b('\n\x14\x63ommon_service.proto\x12\x0erasnet.service\"\x06\n\x04VoidB\x1d\n\x1borg.rasdaman.rasnet.serviceb\x06proto3')
)




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='rasnet.service.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=46,
)

DESCRIPTOR.message_types_by_name['Void'] = _VOID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'common_service_pb2'
  # @@protoc_insertion_point(class_scope:rasnet.service.Void)
  })
_sym_db.RegisterMessage(Void)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
