# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rasmgr_client_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rasdapy.stubs import common_service_pb2 as common__service__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rasmgr_client_service.proto',
  package='rasnet.service',
  syntax='proto3',
  serialized_options=_b('\n\033org.rasdaman.rasnet.service\200\001\000\210\001\000'),
  serialized_pb=_b('\n\x1brasmgr_client_service.proto\x12\x0erasnet.service\x1a\x14\x63ommon_service.proto\"U\n\nConnectReq\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x14\n\x0cpasswordHash\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\x12\x10\n\x08hostName\x18\x04 \x01(\t\"9\n\x0b\x43onnectRepl\x12\x10\n\x08\x63lientId\x18\x01 \x01(\r\x12\x18\n\x10keepAliveTimeout\x18\x02 \x01(\x05\"!\n\rDisconnectReq\x12\x10\n\x08\x63lientId\x18\x01 \x01(\r\"3\n\tOpenDbReq\x12\x10\n\x08\x63lientId\x18\x01 \x01(\r\x12\x14\n\x0c\x64\x61tabaseName\x18\x02 \x01(\t\"`\n\nOpenDbRepl\x12\x17\n\x0f\x63lientSessionId\x18\x01 \x01(\r\x12\x13\n\x0b\x64\x62SessionId\x18\x02 \x01(\r\x12\x16\n\x0eserverHostName\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\r\"3\n\nCloseDbReq\x12\x10\n\x08\x63lientId\x18\x01 \x01(\r\x12\x13\n\x0b\x64\x62SessionId\x18\x02 \x01(\r\" \n\x0cKeepAliveReq\x12\x10\n\x08\x63lientId\x18\x01 \x01(\r2\xdb\x02\n\x13RasmgrClientService\x12\x42\n\x07\x43onnect\x12\x1a.rasnet.service.ConnectReq\x1a\x1b.rasnet.service.ConnectRepl\x12\x41\n\nDisconnect\x12\x1d.rasnet.service.DisconnectReq\x1a\x14.rasnet.service.Void\x12?\n\x06OpenDb\x12\x19.rasnet.service.OpenDbReq\x1a\x1a.rasnet.service.OpenDbRepl\x12;\n\x07\x43loseDb\x12\x1a.rasnet.service.CloseDbReq\x1a\x14.rasnet.service.Void\x12?\n\tKeepAlive\x12\x1c.rasnet.service.KeepAliveReq\x1a\x14.rasnet.service.VoidB#\n\x1borg.rasdaman.rasnet.service\x80\x01\x00\x88\x01\x00\x62\x06proto3')
  ,
  dependencies=[common__service__pb2.DESCRIPTOR,])




_CONNECTREQ = _descriptor.Descriptor(
  name='ConnectReq',
  full_name='rasnet.service.ConnectReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userName', full_name='rasnet.service.ConnectReq.userName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passwordHash', full_name='rasnet.service.ConnectReq.passwordHash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='rasnet.service.ConnectReq.token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hostName', full_name='rasnet.service.ConnectReq.hostName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=154,
)


_CONNECTREPL = _descriptor.Descriptor(
  name='ConnectRepl',
  full_name='rasnet.service.ConnectRepl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientId', full_name='rasnet.service.ConnectRepl.clientId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keepAliveTimeout', full_name='rasnet.service.ConnectRepl.keepAliveTimeout', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=213,
)


_DISCONNECTREQ = _descriptor.Descriptor(
  name='DisconnectReq',
  full_name='rasnet.service.DisconnectReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientId', full_name='rasnet.service.DisconnectReq.clientId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=248,
)


_OPENDBREQ = _descriptor.Descriptor(
  name='OpenDbReq',
  full_name='rasnet.service.OpenDbReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientId', full_name='rasnet.service.OpenDbReq.clientId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='databaseName', full_name='rasnet.service.OpenDbReq.databaseName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=301,
)


_OPENDBREPL = _descriptor.Descriptor(
  name='OpenDbRepl',
  full_name='rasnet.service.OpenDbRepl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientSessionId', full_name='rasnet.service.OpenDbRepl.clientSessionId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dbSessionId', full_name='rasnet.service.OpenDbRepl.dbSessionId', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverHostName', full_name='rasnet.service.OpenDbRepl.serverHostName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='rasnet.service.OpenDbRepl.port', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=399,
)


_CLOSEDBREQ = _descriptor.Descriptor(
  name='CloseDbReq',
  full_name='rasnet.service.CloseDbReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientId', full_name='rasnet.service.CloseDbReq.clientId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dbSessionId', full_name='rasnet.service.CloseDbReq.dbSessionId', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=452,
)


_KEEPALIVEREQ = _descriptor.Descriptor(
  name='KeepAliveReq',
  full_name='rasnet.service.KeepAliveReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientId', full_name='rasnet.service.KeepAliveReq.clientId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=486,
)

DESCRIPTOR.message_types_by_name['ConnectReq'] = _CONNECTREQ
DESCRIPTOR.message_types_by_name['ConnectRepl'] = _CONNECTREPL
DESCRIPTOR.message_types_by_name['DisconnectReq'] = _DISCONNECTREQ
DESCRIPTOR.message_types_by_name['OpenDbReq'] = _OPENDBREQ
DESCRIPTOR.message_types_by_name['OpenDbRepl'] = _OPENDBREPL
DESCRIPTOR.message_types_by_name['CloseDbReq'] = _CLOSEDBREQ
DESCRIPTOR.message_types_by_name['KeepAliveReq'] = _KEEPALIVEREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectReq = _reflection.GeneratedProtocolMessageType('ConnectReq', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTREQ,
  __module__ = 'rasmgr_client_service_pb2'
  # @@protoc_insertion_point(class_scope:rasnet.service.ConnectReq)
  ))
_sym_db.RegisterMessage(ConnectReq)

ConnectRepl = _reflection.GeneratedProtocolMessageType('ConnectRepl', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTREPL,
  __module__ = 'rasmgr_client_service_pb2'
  # @@protoc_insertion_point(class_scope:rasnet.service.ConnectRepl)
  ))
_sym_db.RegisterMessage(ConnectRepl)

DisconnectReq = _reflection.GeneratedProtocolMessageType('DisconnectReq', (_message.Message,), dict(
  DESCRIPTOR = _DISCONNECTREQ,
  __module__ = 'rasmgr_client_service_pb2'
  # @@protoc_insertion_point(class_scope:rasnet.service.DisconnectReq)
  ))
_sym_db.RegisterMessage(DisconnectReq)

OpenDbReq = _reflection.GeneratedProtocolMessageType('OpenDbReq', (_message.Message,), dict(
  DESCRIPTOR = _OPENDBREQ,
  __module__ = 'rasmgr_client_service_pb2'
  # @@protoc_insertion_point(class_scope:rasnet.service.OpenDbReq)
  ))
_sym_db.RegisterMessage(OpenDbReq)

OpenDbRepl = _reflection.GeneratedProtocolMessageType('OpenDbRepl', (_message.Message,), dict(
  DESCRIPTOR = _OPENDBREPL,
  __module__ = 'rasmgr_client_service_pb2'
  # @@protoc_insertion_point(class_scope:rasnet.service.OpenDbRepl)
  ))
_sym_db.RegisterMessage(OpenDbRepl)

CloseDbReq = _reflection.GeneratedProtocolMessageType('CloseDbReq', (_message.Message,), dict(
  DESCRIPTOR = _CLOSEDBREQ,
  __module__ = 'rasmgr_client_service_pb2'
  # @@protoc_insertion_point(class_scope:rasnet.service.CloseDbReq)
  ))
_sym_db.RegisterMessage(CloseDbReq)

KeepAliveReq = _reflection.GeneratedProtocolMessageType('KeepAliveReq', (_message.Message,), dict(
  DESCRIPTOR = _KEEPALIVEREQ,
  __module__ = 'rasmgr_client_service_pb2'
  # @@protoc_insertion_point(class_scope:rasnet.service.KeepAliveReq)
  ))
_sym_db.RegisterMessage(KeepAliveReq)


DESCRIPTOR._options = None

_RASMGRCLIENTSERVICE = _descriptor.ServiceDescriptor(
  name='RasmgrClientService',
  full_name='rasnet.service.RasmgrClientService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=489,
  serialized_end=836,
  methods=[
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='rasnet.service.RasmgrClientService.Connect',
    index=0,
    containing_service=None,
    input_type=_CONNECTREQ,
    output_type=_CONNECTREPL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Disconnect',
    full_name='rasnet.service.RasmgrClientService.Disconnect',
    index=1,
    containing_service=None,
    input_type=_DISCONNECTREQ,
    output_type=common__service__pb2._VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='OpenDb',
    full_name='rasnet.service.RasmgrClientService.OpenDb',
    index=2,
    containing_service=None,
    input_type=_OPENDBREQ,
    output_type=_OPENDBREPL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CloseDb',
    full_name='rasnet.service.RasmgrClientService.CloseDb',
    index=3,
    containing_service=None,
    input_type=_CLOSEDBREQ,
    output_type=common__service__pb2._VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='KeepAlive',
    full_name='rasnet.service.RasmgrClientService.KeepAlive',
    index=4,
    containing_service=None,
    input_type=_KEEPALIVEREQ,
    output_type=common__service__pb2._VOID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RASMGRCLIENTSERVICE)

DESCRIPTOR.services_by_name['RasmgrClientService'] = _RASMGRCLIENTSERVICE

# @@protoc_insertion_point(module_scope)
