// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.rasdaman.rasnet.message;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServiceRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 id = 1;
    /**
     * <code>required uint64 id = 1;</code>
     *
     * <pre>
     *This id identifies the request for a particular client
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required uint64 id = 1;</code>
     *
     * <pre>
     *This id identifies the request for a particular client
     * </pre>
     */
    long getId();

    // required string method_name = 2;
    /**
     * <code>required string method_name = 2;</code>
     *
     * <pre>
     *The method name uniquely identifies the method the client wants to call.
     * </pre>
     */
    boolean hasMethodName();
    /**
     * <code>required string method_name = 2;</code>
     *
     * <pre>
     *The method name uniquely identifies the method the client wants to call.
     * </pre>
     */
    java.lang.String getMethodName();
    /**
     * <code>required string method_name = 2;</code>
     *
     * <pre>
     *The method name uniquely identifies the method the client wants to call.
     * </pre>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    // required bytes input_value = 3;
    /**
     * <code>required bytes input_value = 3;</code>
     *
     * <pre>
     *The input value represents the serialized request parameter
     * </pre>
     */
    boolean hasInputValue();
    /**
     * <code>required bytes input_value = 3;</code>
     *
     * <pre>
     *The input value represents the serialized request parameter
     * </pre>
     */
    com.google.protobuf.ByteString getInputValue();
  }
  /**
   * Protobuf type {@code rasnet.ServiceRequest}
   *
   * <pre>
   **
   * A ServiceRequest is sent by a client to ask the service provider to execute a
   * task and return a response.
   * </pre>
   */
  public static final class ServiceRequest extends
      com.google.protobuf.GeneratedMessage
      implements ServiceRequestOrBuilder {
    // Use ServiceRequest.newBuilder() to construct.
    private ServiceRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServiceRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServiceRequest defaultInstance;
    public static ServiceRequest getDefaultInstance() {
      return defaultInstance;
    }

    public ServiceRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              methodName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              inputValue_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rasdaman.rasnet.message.Service.internal_static_rasnet_ServiceRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rasdaman.rasnet.message.Service.internal_static_rasnet_ServiceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rasdaman.rasnet.message.Service.ServiceRequest.class, org.rasdaman.rasnet.message.Service.ServiceRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<ServiceRequest> PARSER =
        new com.google.protobuf.AbstractParser<ServiceRequest>() {
      public ServiceRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServiceRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required uint64 id = 1;</code>
     *
     * <pre>
     *This id identifies the request for a particular client
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 id = 1;</code>
     *
     * <pre>
     *This id identifies the request for a particular client
     * </pre>
     */
    public long getId() {
      return id_;
    }

    // required string method_name = 2;
    public static final int METHOD_NAME_FIELD_NUMBER = 2;
    private java.lang.Object methodName_;
    /**
     * <code>required string method_name = 2;</code>
     *
     * <pre>
     *The method name uniquely identifies the method the client wants to call.
     * </pre>
     */
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string method_name = 2;</code>
     *
     * <pre>
     *The method name uniquely identifies the method the client wants to call.
     * </pre>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          methodName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string method_name = 2;</code>
     *
     * <pre>
     *The method name uniquely identifies the method the client wants to call.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes input_value = 3;
    public static final int INPUT_VALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString inputValue_;
    /**
     * <code>required bytes input_value = 3;</code>
     *
     * <pre>
     *The input value represents the serialized request parameter
     * </pre>
     */
    public boolean hasInputValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes input_value = 3;</code>
     *
     * <pre>
     *The input value represents the serialized request parameter
     * </pre>
     */
    public com.google.protobuf.ByteString getInputValue() {
      return inputValue_;
    }

    private void initFields() {
      id_ = 0L;
      methodName_ = "";
      inputValue_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInputValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, inputValue_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMethodNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, inputValue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.rasdaman.rasnet.message.Service.ServiceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.rasdaman.rasnet.message.Service.ServiceRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rasnet.ServiceRequest}
     *
     * <pre>
     **
     * A ServiceRequest is sent by a client to ask the service provider to execute a
     * task and return a response.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.rasdaman.rasnet.message.Service.ServiceRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rasdaman.rasnet.message.Service.internal_static_rasnet_ServiceRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rasdaman.rasnet.message.Service.internal_static_rasnet_ServiceRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rasdaman.rasnet.message.Service.ServiceRequest.class, org.rasdaman.rasnet.message.Service.ServiceRequest.Builder.class);
      }

      // Construct using org.rasdaman.rasnet.message.Service.ServiceRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        methodName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        inputValue_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rasdaman.rasnet.message.Service.internal_static_rasnet_ServiceRequest_descriptor;
      }

      public org.rasdaman.rasnet.message.Service.ServiceRequest getDefaultInstanceForType() {
        return org.rasdaman.rasnet.message.Service.ServiceRequest.getDefaultInstance();
      }

      public org.rasdaman.rasnet.message.Service.ServiceRequest build() {
        org.rasdaman.rasnet.message.Service.ServiceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rasdaman.rasnet.message.Service.ServiceRequest buildPartial() {
        org.rasdaman.rasnet.message.Service.ServiceRequest result = new org.rasdaman.rasnet.message.Service.ServiceRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.methodName_ = methodName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.inputValue_ = inputValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rasdaman.rasnet.message.Service.ServiceRequest) {
          return mergeFrom((org.rasdaman.rasnet.message.Service.ServiceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rasdaman.rasnet.message.Service.ServiceRequest other) {
        if (other == org.rasdaman.rasnet.message.Service.ServiceRequest.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasMethodName()) {
          bitField0_ |= 0x00000002;
          methodName_ = other.methodName_;
          onChanged();
        }
        if (other.hasInputValue()) {
          setInputValue(other.getInputValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {

          return false;
        }
        if (!hasMethodName()) {

          return false;
        }
        if (!hasInputValue()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rasdaman.rasnet.message.Service.ServiceRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rasdaman.rasnet.message.Service.ServiceRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 id = 1;
      private long id_ ;
      /**
       * <code>required uint64 id = 1;</code>
       *
       * <pre>
       *This id identifies the request for a particular client
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 id = 1;</code>
       *
       * <pre>
       *This id identifies the request for a particular client
       * </pre>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required uint64 id = 1;</code>
       *
       * <pre>
       *This id identifies the request for a particular client
       * </pre>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 id = 1;</code>
       *
       * <pre>
       *This id identifies the request for a particular client
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // required string method_name = 2;
      private java.lang.Object methodName_ = "";
      /**
       * <code>required string method_name = 2;</code>
       *
       * <pre>
       *The method name uniquely identifies the method the client wants to call.
       * </pre>
       */
      public boolean hasMethodName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string method_name = 2;</code>
       *
       * <pre>
       *The method name uniquely identifies the method the client wants to call.
       * </pre>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string method_name = 2;</code>
       *
       * <pre>
       *The method name uniquely identifies the method the client wants to call.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string method_name = 2;</code>
       *
       * <pre>
       *The method name uniquely identifies the method the client wants to call.
       * </pre>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string method_name = 2;</code>
       *
       * <pre>
       *The method name uniquely identifies the method the client wants to call.
       * </pre>
       */
      public Builder clearMethodName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>required string method_name = 2;</code>
       *
       * <pre>
       *The method name uniquely identifies the method the client wants to call.
       * </pre>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }

      // required bytes input_value = 3;
      private com.google.protobuf.ByteString inputValue_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes input_value = 3;</code>
       *
       * <pre>
       *The input value represents the serialized request parameter
       * </pre>
       */
      public boolean hasInputValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes input_value = 3;</code>
       *
       * <pre>
       *The input value represents the serialized request parameter
       * </pre>
       */
      public com.google.protobuf.ByteString getInputValue() {
        return inputValue_;
      }
      /**
       * <code>required bytes input_value = 3;</code>
       *
       * <pre>
       *The input value represents the serialized request parameter
       * </pre>
       */
      public Builder setInputValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        inputValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes input_value = 3;</code>
       *
       * <pre>
       *The input value represents the serialized request parameter
       * </pre>
       */
      public Builder clearInputValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        inputValue_ = getDefaultInstance().getInputValue();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rasnet.ServiceRequest)
    }

    static {
      defaultInstance = new ServiceRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rasnet.ServiceRequest)
  }

  public interface ServiceResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 id = 1;
    /**
     * <code>required uint64 id = 1;</code>
     *
     * <pre>
     *The id uniquely identifies the service call for the client.
     *It must be the same as the one in the ServiceRequest message.
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required uint64 id = 1;</code>
     *
     * <pre>
     *The id uniquely identifies the service call for the client.
     *It must be the same as the one in the ServiceRequest message.
     * </pre>
     */
    long getId();

    // optional bytes output_value = 2;
    /**
     * <code>optional bytes output_value = 2;</code>
     *
     * <pre>
     *The output value is the string serialization of the output parameter.
     *This is optional because a ServiceResponse might be an error or a valid result.
     * </pre>
     */
    boolean hasOutputValue();
    /**
     * <code>optional bytes output_value = 2;</code>
     *
     * <pre>
     *The output value is the string serialization of the output parameter.
     *This is optional because a ServiceResponse might be an error or a valid result.
     * </pre>
     */
    com.google.protobuf.ByteString getOutputValue();

    // optional string error = 3;
    /**
     * <code>optional string error = 3;</code>
     *
     * <pre>
     *The error component is a human readable string representing an error.
     * </pre>
     */
    boolean hasError();
    /**
     * <code>optional string error = 3;</code>
     *
     * <pre>
     *The error component is a human readable string representing an error.
     * </pre>
     */
    java.lang.String getError();
    /**
     * <code>optional string error = 3;</code>
     *
     * <pre>
     *The error component is a human readable string representing an error.
     * </pre>
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * Protobuf type {@code rasnet.ServiceResponse}
   *
   * <pre>
   **
   * A ServiceResponse is always sent by a service provider in response to a client's request.
   * </pre>
   */
  public static final class ServiceResponse extends
      com.google.protobuf.GeneratedMessage
      implements ServiceResponseOrBuilder {
    // Use ServiceResponse.newBuilder() to construct.
    private ServiceResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServiceResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServiceResponse defaultInstance;
    public static ServiceResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ServiceResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              outputValue_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              error_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rasdaman.rasnet.message.Service.internal_static_rasnet_ServiceResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rasdaman.rasnet.message.Service.internal_static_rasnet_ServiceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rasdaman.rasnet.message.Service.ServiceResponse.class, org.rasdaman.rasnet.message.Service.ServiceResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ServiceResponse> PARSER =
        new com.google.protobuf.AbstractParser<ServiceResponse>() {
      public ServiceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServiceResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required uint64 id = 1;</code>
     *
     * <pre>
     *The id uniquely identifies the service call for the client.
     *It must be the same as the one in the ServiceRequest message.
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 id = 1;</code>
     *
     * <pre>
     *The id uniquely identifies the service call for the client.
     *It must be the same as the one in the ServiceRequest message.
     * </pre>
     */
    public long getId() {
      return id_;
    }

    // optional bytes output_value = 2;
    public static final int OUTPUT_VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString outputValue_;
    /**
     * <code>optional bytes output_value = 2;</code>
     *
     * <pre>
     *The output value is the string serialization of the output parameter.
     *This is optional because a ServiceResponse might be an error or a valid result.
     * </pre>
     */
    public boolean hasOutputValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes output_value = 2;</code>
     *
     * <pre>
     *The output value is the string serialization of the output parameter.
     *This is optional because a ServiceResponse might be an error or a valid result.
     * </pre>
     */
    public com.google.protobuf.ByteString getOutputValue() {
      return outputValue_;
    }

    // optional string error = 3;
    public static final int ERROR_FIELD_NUMBER = 3;
    private java.lang.Object error_;
    /**
     * <code>optional string error = 3;</code>
     *
     * <pre>
     *The error component is a human readable string representing an error.
     * </pre>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string error = 3;</code>
     *
     * <pre>
     *The error component is a human readable string representing an error.
     * </pre>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          error_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error = 3;</code>
     *
     * <pre>
     *The error component is a human readable string representing an error.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0L;
      outputValue_ = com.google.protobuf.ByteString.EMPTY;
      error_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, outputValue_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getErrorBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, outputValue_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getErrorBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.rasdaman.rasnet.message.Service.ServiceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.Service.ServiceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.rasdaman.rasnet.message.Service.ServiceResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rasnet.ServiceResponse}
     *
     * <pre>
     **
     * A ServiceResponse is always sent by a service provider in response to a client's request.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.rasdaman.rasnet.message.Service.ServiceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rasdaman.rasnet.message.Service.internal_static_rasnet_ServiceResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rasdaman.rasnet.message.Service.internal_static_rasnet_ServiceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rasdaman.rasnet.message.Service.ServiceResponse.class, org.rasdaman.rasnet.message.Service.ServiceResponse.Builder.class);
      }

      // Construct using org.rasdaman.rasnet.message.Service.ServiceResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        outputValue_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        error_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rasdaman.rasnet.message.Service.internal_static_rasnet_ServiceResponse_descriptor;
      }

      public org.rasdaman.rasnet.message.Service.ServiceResponse getDefaultInstanceForType() {
        return org.rasdaman.rasnet.message.Service.ServiceResponse.getDefaultInstance();
      }

      public org.rasdaman.rasnet.message.Service.ServiceResponse build() {
        org.rasdaman.rasnet.message.Service.ServiceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rasdaman.rasnet.message.Service.ServiceResponse buildPartial() {
        org.rasdaman.rasnet.message.Service.ServiceResponse result = new org.rasdaman.rasnet.message.Service.ServiceResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.outputValue_ = outputValue_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.error_ = error_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rasdaman.rasnet.message.Service.ServiceResponse) {
          return mergeFrom((org.rasdaman.rasnet.message.Service.ServiceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rasdaman.rasnet.message.Service.ServiceResponse other) {
        if (other == org.rasdaman.rasnet.message.Service.ServiceResponse.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasOutputValue()) {
          setOutputValue(other.getOutputValue());
        }
        if (other.hasError()) {
          bitField0_ |= 0x00000004;
          error_ = other.error_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rasdaman.rasnet.message.Service.ServiceResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rasdaman.rasnet.message.Service.ServiceResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 id = 1;
      private long id_ ;
      /**
       * <code>required uint64 id = 1;</code>
       *
       * <pre>
       *The id uniquely identifies the service call for the client.
       *It must be the same as the one in the ServiceRequest message.
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 id = 1;</code>
       *
       * <pre>
       *The id uniquely identifies the service call for the client.
       *It must be the same as the one in the ServiceRequest message.
       * </pre>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required uint64 id = 1;</code>
       *
       * <pre>
       *The id uniquely identifies the service call for the client.
       *It must be the same as the one in the ServiceRequest message.
       * </pre>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 id = 1;</code>
       *
       * <pre>
       *The id uniquely identifies the service call for the client.
       *It must be the same as the one in the ServiceRequest message.
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // optional bytes output_value = 2;
      private com.google.protobuf.ByteString outputValue_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes output_value = 2;</code>
       *
       * <pre>
       *The output value is the string serialization of the output parameter.
       *This is optional because a ServiceResponse might be an error or a valid result.
       * </pre>
       */
      public boolean hasOutputValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes output_value = 2;</code>
       *
       * <pre>
       *The output value is the string serialization of the output parameter.
       *This is optional because a ServiceResponse might be an error or a valid result.
       * </pre>
       */
      public com.google.protobuf.ByteString getOutputValue() {
        return outputValue_;
      }
      /**
       * <code>optional bytes output_value = 2;</code>
       *
       * <pre>
       *The output value is the string serialization of the output parameter.
       *This is optional because a ServiceResponse might be an error or a valid result.
       * </pre>
       */
      public Builder setOutputValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        outputValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes output_value = 2;</code>
       *
       * <pre>
       *The output value is the string serialization of the output parameter.
       *This is optional because a ServiceResponse might be an error or a valid result.
       * </pre>
       */
      public Builder clearOutputValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        outputValue_ = getDefaultInstance().getOutputValue();
        onChanged();
        return this;
      }

      // optional string error = 3;
      private java.lang.Object error_ = "";
      /**
       * <code>optional string error = 3;</code>
       *
       * <pre>
       *The error component is a human readable string representing an error.
       * </pre>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string error = 3;</code>
       *
       * <pre>
       *The error component is a human readable string representing an error.
       * </pre>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error = 3;</code>
       *
       * <pre>
       *The error component is a human readable string representing an error.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error = 3;</code>
       *
       * <pre>
       *The error component is a human readable string representing an error.
       * </pre>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 3;</code>
       *
       * <pre>
       *The error component is a human readable string representing an error.
       * </pre>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000004);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 3;</code>
       *
       * <pre>
       *The error component is a human readable string representing an error.
       * </pre>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        error_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rasnet.ServiceResponse)
    }

    static {
      defaultInstance = new ServiceResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rasnet.ServiceResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rasnet_ServiceRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rasnet_ServiceRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rasnet_ServiceResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rasnet_ServiceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\006rasnet\"F\n\016ServiceReques" +
      "t\022\n\n\002id\030\001 \002(\004\022\023\n\013method_name\030\002 \002(\t\022\023\n\013in" +
      "put_value\030\003 \002(\014\"B\n\017ServiceResponse\022\n\n\002id" +
      "\030\001 \002(\004\022\024\n\014output_value\030\002 \001(\014\022\r\n\005error\030\003 " +
      "\001(\tB\035\n\033org.rasdaman.rasnet.message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rasnet_ServiceRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rasnet_ServiceRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rasnet_ServiceRequest_descriptor,
              new java.lang.String[] { "Id", "MethodName", "InputValue", });
          internal_static_rasnet_ServiceResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_rasnet_ServiceResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rasnet_ServiceResponse_descriptor,
              new java.lang.String[] { "Id", "OutputValue", "Error", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
