// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_mess.proto

package org.rasdaman.rasnet.message;

public final class TestMess {
  private TestMess() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DummyRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 requestNo = 1;
    /**
     * <code>optional int32 requestNo = 1;</code>
     */
    boolean hasRequestNo();
    /**
     * <code>optional int32 requestNo = 1;</code>
     */
    int getRequestNo();
  }
  /**
   * Protobuf type {@code rnp_test.DummyRequest}
   *
   * <pre>
   *An empty message that can be sent as a request
   * </pre>
   */
  public static final class DummyRequest extends
      com.google.protobuf.GeneratedMessage
      implements DummyRequestOrBuilder {
    // Use DummyRequest.newBuilder() to construct.
    private DummyRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DummyRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DummyRequest defaultInstance;
    public static DummyRequest getDefaultInstance() {
      return defaultInstance;
    }

    public DummyRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DummyRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              requestNo_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_DummyRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_DummyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rasdaman.rasnet.message.TestMess.DummyRequest.class, org.rasdaman.rasnet.message.TestMess.DummyRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<DummyRequest> PARSER =
        new com.google.protobuf.AbstractParser<DummyRequest>() {
      public DummyRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DummyRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DummyRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 requestNo = 1;
    public static final int REQUESTNO_FIELD_NUMBER = 1;
    private int requestNo_;
    /**
     * <code>optional int32 requestNo = 1;</code>
     */
    public boolean hasRequestNo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 requestNo = 1;</code>
     */
    public int getRequestNo() {
      return requestNo_;
    }

    private void initFields() {
      requestNo_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, requestNo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, requestNo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.rasdaman.rasnet.message.TestMess.DummyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.rasdaman.rasnet.message.TestMess.DummyRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rnp_test.DummyRequest}
     *
     * <pre>
     *An empty message that can be sent as a request
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.rasdaman.rasnet.message.TestMess.DummyRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_DummyRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_DummyRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rasdaman.rasnet.message.TestMess.DummyRequest.class, org.rasdaman.rasnet.message.TestMess.DummyRequest.Builder.class);
      }

      // Construct using org.rasdaman.rasnet.message.TestMess.DummyRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        requestNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_DummyRequest_descriptor;
      }

      public org.rasdaman.rasnet.message.TestMess.DummyRequest getDefaultInstanceForType() {
        return org.rasdaman.rasnet.message.TestMess.DummyRequest.getDefaultInstance();
      }

      public org.rasdaman.rasnet.message.TestMess.DummyRequest build() {
        org.rasdaman.rasnet.message.TestMess.DummyRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rasdaman.rasnet.message.TestMess.DummyRequest buildPartial() {
        org.rasdaman.rasnet.message.TestMess.DummyRequest result = new org.rasdaman.rasnet.message.TestMess.DummyRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestNo_ = requestNo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rasdaman.rasnet.message.TestMess.DummyRequest) {
          return mergeFrom((org.rasdaman.rasnet.message.TestMess.DummyRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rasdaman.rasnet.message.TestMess.DummyRequest other) {
        if (other == org.rasdaman.rasnet.message.TestMess.DummyRequest.getDefaultInstance()) return this;
        if (other.hasRequestNo()) {
          setRequestNo(other.getRequestNo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rasdaman.rasnet.message.TestMess.DummyRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rasdaman.rasnet.message.TestMess.DummyRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 requestNo = 1;
      private int requestNo_ ;
      /**
       * <code>optional int32 requestNo = 1;</code>
       */
      public boolean hasRequestNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 requestNo = 1;</code>
       */
      public int getRequestNo() {
        return requestNo_;
      }
      /**
       * <code>optional int32 requestNo = 1;</code>
       */
      public Builder setRequestNo(int value) {
        bitField0_ |= 0x00000001;
        requestNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 requestNo = 1;</code>
       */
      public Builder clearRequestNo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestNo_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rnp_test.DummyRequest)
    }

    static {
      defaultInstance = new DummyRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rnp_test.DummyRequest)
  }

  public interface DummyReplyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code rnp_test.DummyReply}
   *
   * <pre>
   *An empty message that can be sent as a reply to a request
   * </pre>
   */
  public static final class DummyReply extends
      com.google.protobuf.GeneratedMessage
      implements DummyReplyOrBuilder {
    // Use DummyReply.newBuilder() to construct.
    private DummyReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DummyReply(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DummyReply defaultInstance;
    public static DummyReply getDefaultInstance() {
      return defaultInstance;
    }

    public DummyReply getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DummyReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_DummyReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_DummyReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rasdaman.rasnet.message.TestMess.DummyReply.class, org.rasdaman.rasnet.message.TestMess.DummyReply.Builder.class);
    }

    public static com.google.protobuf.Parser<DummyReply> PARSER =
        new com.google.protobuf.AbstractParser<DummyReply>() {
      public DummyReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DummyReply(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DummyReply> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.rasdaman.rasnet.message.TestMess.DummyReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.TestMess.DummyReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.rasdaman.rasnet.message.TestMess.DummyReply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rnp_test.DummyReply}
     *
     * <pre>
     *An empty message that can be sent as a reply to a request
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.rasdaman.rasnet.message.TestMess.DummyReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_DummyReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_DummyReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rasdaman.rasnet.message.TestMess.DummyReply.class, org.rasdaman.rasnet.message.TestMess.DummyReply.Builder.class);
      }

      // Construct using org.rasdaman.rasnet.message.TestMess.DummyReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_DummyReply_descriptor;
      }

      public org.rasdaman.rasnet.message.TestMess.DummyReply getDefaultInstanceForType() {
        return org.rasdaman.rasnet.message.TestMess.DummyReply.getDefaultInstance();
      }

      public org.rasdaman.rasnet.message.TestMess.DummyReply build() {
        org.rasdaman.rasnet.message.TestMess.DummyReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rasdaman.rasnet.message.TestMess.DummyReply buildPartial() {
        org.rasdaman.rasnet.message.TestMess.DummyReply result = new org.rasdaman.rasnet.message.TestMess.DummyReply(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rasdaman.rasnet.message.TestMess.DummyReply) {
          return mergeFrom((org.rasdaman.rasnet.message.TestMess.DummyReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rasdaman.rasnet.message.TestMess.DummyReply other) {
        if (other == org.rasdaman.rasnet.message.TestMess.DummyReply.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rasdaman.rasnet.message.TestMess.DummyReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rasdaman.rasnet.message.TestMess.DummyReply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rnp_test.DummyReply)
    }

    static {
      defaultInstance = new DummyReply(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rnp_test.DummyReply)
  }

  public interface RequestTypeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string req = 1;
    /**
     * <code>required string req = 1;</code>
     */
    boolean hasReq();
    /**
     * <code>required string req = 1;</code>
     */
    java.lang.String getReq();
    /**
     * <code>required string req = 1;</code>
     */
    com.google.protobuf.ByteString
        getReqBytes();
  }
  /**
   * Protobuf type {@code rnp_test.RequestType}
   */
  public static final class RequestType extends
      com.google.protobuf.GeneratedMessage
      implements RequestTypeOrBuilder {
    // Use RequestType.newBuilder() to construct.
    private RequestType(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RequestType(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RequestType defaultInstance;
    public static RequestType getDefaultInstance() {
      return defaultInstance;
    }

    public RequestType getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RequestType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              req_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_RequestType_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_RequestType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rasdaman.rasnet.message.TestMess.RequestType.class, org.rasdaman.rasnet.message.TestMess.RequestType.Builder.class);
    }

    public static com.google.protobuf.Parser<RequestType> PARSER =
        new com.google.protobuf.AbstractParser<RequestType>() {
      public RequestType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestType(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RequestType> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string req = 1;
    public static final int REQ_FIELD_NUMBER = 1;
    private java.lang.Object req_;
    /**
     * <code>required string req = 1;</code>
     */
    public boolean hasReq() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string req = 1;</code>
     */
    public java.lang.String getReq() {
      java.lang.Object ref = req_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          req_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string req = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReqBytes() {
      java.lang.Object ref = req_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        req_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      req_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReq()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getReqBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getReqBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.rasdaman.rasnet.message.TestMess.RequestType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.TestMess.RequestType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.TestMess.RequestType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.TestMess.RequestType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.TestMess.RequestType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.TestMess.RequestType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.TestMess.RequestType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rasdaman.rasnet.message.TestMess.RequestType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.TestMess.RequestType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.TestMess.RequestType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.rasdaman.rasnet.message.TestMess.RequestType prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rnp_test.RequestType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.rasdaman.rasnet.message.TestMess.RequestTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_RequestType_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_RequestType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rasdaman.rasnet.message.TestMess.RequestType.class, org.rasdaman.rasnet.message.TestMess.RequestType.Builder.class);
      }

      // Construct using org.rasdaman.rasnet.message.TestMess.RequestType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        req_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_RequestType_descriptor;
      }

      public org.rasdaman.rasnet.message.TestMess.RequestType getDefaultInstanceForType() {
        return org.rasdaman.rasnet.message.TestMess.RequestType.getDefaultInstance();
      }

      public org.rasdaman.rasnet.message.TestMess.RequestType build() {
        org.rasdaman.rasnet.message.TestMess.RequestType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rasdaman.rasnet.message.TestMess.RequestType buildPartial() {
        org.rasdaman.rasnet.message.TestMess.RequestType result = new org.rasdaman.rasnet.message.TestMess.RequestType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.req_ = req_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rasdaman.rasnet.message.TestMess.RequestType) {
          return mergeFrom((org.rasdaman.rasnet.message.TestMess.RequestType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rasdaman.rasnet.message.TestMess.RequestType other) {
        if (other == org.rasdaman.rasnet.message.TestMess.RequestType.getDefaultInstance()) return this;
        if (other.hasReq()) {
          bitField0_ |= 0x00000001;
          req_ = other.req_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReq()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rasdaman.rasnet.message.TestMess.RequestType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rasdaman.rasnet.message.TestMess.RequestType) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string req = 1;
      private java.lang.Object req_ = "";
      /**
       * <code>required string req = 1;</code>
       */
      public boolean hasReq() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string req = 1;</code>
       */
      public java.lang.String getReq() {
        java.lang.Object ref = req_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          req_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string req = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReqBytes() {
        java.lang.Object ref = req_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          req_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string req = 1;</code>
       */
      public Builder setReq(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        req_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string req = 1;</code>
       */
      public Builder clearReq() {
        bitField0_ = (bitField0_ & ~0x00000001);
        req_ = getDefaultInstance().getReq();
        onChanged();
        return this;
      }
      /**
       * <code>required string req = 1;</code>
       */
      public Builder setReqBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        req_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rnp_test.RequestType)
    }

    static {
      defaultInstance = new RequestType(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rnp_test.RequestType)
  }

  public interface ResponseTypeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string repl = 1;
    /**
     * <code>required string repl = 1;</code>
     */
    boolean hasRepl();
    /**
     * <code>required string repl = 1;</code>
     */
    java.lang.String getRepl();
    /**
     * <code>required string repl = 1;</code>
     */
    com.google.protobuf.ByteString
        getReplBytes();
  }
  /**
   * Protobuf type {@code rnp_test.ResponseType}
   */
  public static final class ResponseType extends
      com.google.protobuf.GeneratedMessage
      implements ResponseTypeOrBuilder {
    // Use ResponseType.newBuilder() to construct.
    private ResponseType(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResponseType(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResponseType defaultInstance;
    public static ResponseType getDefaultInstance() {
      return defaultInstance;
    }

    public ResponseType getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              repl_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_ResponseType_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_ResponseType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rasdaman.rasnet.message.TestMess.ResponseType.class, org.rasdaman.rasnet.message.TestMess.ResponseType.Builder.class);
    }

    public static com.google.protobuf.Parser<ResponseType> PARSER =
        new com.google.protobuf.AbstractParser<ResponseType>() {
      public ResponseType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseType(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseType> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string repl = 1;
    public static final int REPL_FIELD_NUMBER = 1;
    private java.lang.Object repl_;
    /**
     * <code>required string repl = 1;</code>
     */
    public boolean hasRepl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string repl = 1;</code>
     */
    public java.lang.String getRepl() {
      java.lang.Object ref = repl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          repl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string repl = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReplBytes() {
      java.lang.Object ref = repl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        repl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      repl_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRepl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getReplBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getReplBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.rasdaman.rasnet.message.TestMess.ResponseType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.TestMess.ResponseType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.TestMess.ResponseType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.TestMess.ResponseType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.TestMess.ResponseType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.TestMess.ResponseType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.TestMess.ResponseType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rasdaman.rasnet.message.TestMess.ResponseType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.TestMess.ResponseType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.TestMess.ResponseType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.rasdaman.rasnet.message.TestMess.ResponseType prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rnp_test.ResponseType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.rasdaman.rasnet.message.TestMess.ResponseTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_ResponseType_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_ResponseType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rasdaman.rasnet.message.TestMess.ResponseType.class, org.rasdaman.rasnet.message.TestMess.ResponseType.Builder.class);
      }

      // Construct using org.rasdaman.rasnet.message.TestMess.ResponseType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        repl_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rasdaman.rasnet.message.TestMess.internal_static_rnp_test_ResponseType_descriptor;
      }

      public org.rasdaman.rasnet.message.TestMess.ResponseType getDefaultInstanceForType() {
        return org.rasdaman.rasnet.message.TestMess.ResponseType.getDefaultInstance();
      }

      public org.rasdaman.rasnet.message.TestMess.ResponseType build() {
        org.rasdaman.rasnet.message.TestMess.ResponseType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rasdaman.rasnet.message.TestMess.ResponseType buildPartial() {
        org.rasdaman.rasnet.message.TestMess.ResponseType result = new org.rasdaman.rasnet.message.TestMess.ResponseType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.repl_ = repl_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rasdaman.rasnet.message.TestMess.ResponseType) {
          return mergeFrom((org.rasdaman.rasnet.message.TestMess.ResponseType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rasdaman.rasnet.message.TestMess.ResponseType other) {
        if (other == org.rasdaman.rasnet.message.TestMess.ResponseType.getDefaultInstance()) return this;
        if (other.hasRepl()) {
          bitField0_ |= 0x00000001;
          repl_ = other.repl_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRepl()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rasdaman.rasnet.message.TestMess.ResponseType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rasdaman.rasnet.message.TestMess.ResponseType) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string repl = 1;
      private java.lang.Object repl_ = "";
      /**
       * <code>required string repl = 1;</code>
       */
      public boolean hasRepl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string repl = 1;</code>
       */
      public java.lang.String getRepl() {
        java.lang.Object ref = repl_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          repl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string repl = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReplBytes() {
        java.lang.Object ref = repl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          repl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string repl = 1;</code>
       */
      public Builder setRepl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        repl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string repl = 1;</code>
       */
      public Builder clearRepl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        repl_ = getDefaultInstance().getRepl();
        onChanged();
        return this;
      }
      /**
       * <code>required string repl = 1;</code>
       */
      public Builder setReplBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        repl_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rnp_test.ResponseType)
    }

    static {
      defaultInstance = new ResponseType(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:rnp_test.ResponseType)
  }

  /**
   * Protobuf service {@code rnp_test.SearchService}
   *
   * <pre>
   *A simple service that takes a RequestType message as an input parameter
   *and returns a ResponseType message as an output parameter.
   * </pre>
   */
  public static abstract class SearchService
      implements com.google.protobuf.Service {
    protected SearchService() {}

    public interface Interface {
      /**
       * <code>rpc Search(.rnp_test.RequestType) returns (.rnp_test.ResponseType);</code>
       */
      public abstract void search(
          com.google.protobuf.RpcController controller,
          org.rasdaman.rasnet.message.TestMess.RequestType request,
          com.google.protobuf.RpcCallback<org.rasdaman.rasnet.message.TestMess.ResponseType> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new SearchService() {
        @java.lang.Override
        public  void search(
            com.google.protobuf.RpcController controller,
            org.rasdaman.rasnet.message.TestMess.RequestType request,
            com.google.protobuf.RpcCallback<org.rasdaman.rasnet.message.TestMess.ResponseType> done) {
          impl.search(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.search(controller, (org.rasdaman.rasnet.message.TestMess.RequestType)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.rasdaman.rasnet.message.TestMess.RequestType.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.rasdaman.rasnet.message.TestMess.ResponseType.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc Search(.rnp_test.RequestType) returns (.rnp_test.ResponseType);</code>
     */
    public abstract void search(
        com.google.protobuf.RpcController controller,
        org.rasdaman.rasnet.message.TestMess.RequestType request,
        com.google.protobuf.RpcCallback<org.rasdaman.rasnet.message.TestMess.ResponseType> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.rasdaman.rasnet.message.TestMess.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.search(controller, (org.rasdaman.rasnet.message.TestMess.RequestType)request,
            com.google.protobuf.RpcUtil.<org.rasdaman.rasnet.message.TestMess.ResponseType>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.rasdaman.rasnet.message.TestMess.RequestType.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.rasdaman.rasnet.message.TestMess.ResponseType.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.rasdaman.rasnet.message.TestMess.SearchService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void search(
          com.google.protobuf.RpcController controller,
          org.rasdaman.rasnet.message.TestMess.RequestType request,
          com.google.protobuf.RpcCallback<org.rasdaman.rasnet.message.TestMess.ResponseType> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.rasdaman.rasnet.message.TestMess.ResponseType.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.rasdaman.rasnet.message.TestMess.ResponseType.class,
            org.rasdaman.rasnet.message.TestMess.ResponseType.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.rasdaman.rasnet.message.TestMess.ResponseType search(
          com.google.protobuf.RpcController controller,
          org.rasdaman.rasnet.message.TestMess.RequestType request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public org.rasdaman.rasnet.message.TestMess.ResponseType search(
          com.google.protobuf.RpcController controller,
          org.rasdaman.rasnet.message.TestMess.RequestType request)
          throws com.google.protobuf.ServiceException {
        return (org.rasdaman.rasnet.message.TestMess.ResponseType) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.rasdaman.rasnet.message.TestMess.ResponseType.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:rnp_test.SearchService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rnp_test_DummyRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rnp_test_DummyRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rnp_test_DummyReply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rnp_test_DummyReply_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rnp_test_RequestType_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rnp_test_RequestType_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rnp_test_ResponseType_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rnp_test_ResponseType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017test_mess.proto\022\010rnp_test\"!\n\014DummyRequ" +
      "est\022\021\n\trequestNo\030\001 \001(\005\"\014\n\nDummyReply\"\032\n\013" +
      "RequestType\022\013\n\003req\030\001 \002(\t\"\034\n\014ResponseType" +
      "\022\014\n\004repl\030\001 \002(\t2H\n\rSearchService\0227\n\006Searc" +
      "h\022\025.rnp_test.RequestType\032\026.rnp_test.Resp" +
      "onseTypeB#\n\033org.rasdaman.rasnet.message\200" +
      "\001\001\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rnp_test_DummyRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rnp_test_DummyRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rnp_test_DummyRequest_descriptor,
              new java.lang.String[] { "RequestNo", });
          internal_static_rnp_test_DummyReply_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_rnp_test_DummyReply_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rnp_test_DummyReply_descriptor,
              new java.lang.String[] { });
          internal_static_rnp_test_RequestType_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_rnp_test_RequestType_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rnp_test_RequestType_descriptor,
              new java.lang.String[] { "Req", });
          internal_static_rnp_test_ResponseType_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_rnp_test_ResponseType_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rnp_test_ResponseType_descriptor,
              new java.lang.String[] { "Repl", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
