<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns="http://schemas.xmlsoap.org/wsdl/" >
	<message name="GetEndorsingBoarderRequest">
		<part name="body" element=""/>
	</message>
	<message name="GetEndorsingBoarderResponse">
		<part name="body" element=""/>
	</message>
	<portType name="glossaryTerms">
	</portType>
	<!-- omitted types section with content model schema info -->
</definitions>
