<?xml version="1.0" encoding="ISO-8859-1"?>
<comparisonResult xmlns='http://www.opengis.net/crs-nts/1.0' xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmd="http://www.isotc211.org/2005/gmd">
  <equal>false</equal>
  <reason>
  <![CDATA[
[different] Expected element tag name 'GeodeticCRS' but was 'VerticalCRS' - comparing <GeodeticCRS...> at /GeodeticCRS[1] to <VerticalCRS...> at /VerticalCRS[1]
  ]]>
  </reason>
</comparisonResult>