<?xml version="1.0" encoding="ISO-8859-1"?>
<gml:ImageCRS xmlns:gml="http://www.opengis.net/gml/3.2" xmlns="http://www.opengis.net/gml/3.2" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmd="http://www.isotc211.org/2005/gmd" gml:id="img2D">
  <gml:identifier codeSpace="OGP">local/crs/OGC/0.1/Image2D</gml:identifier>
  <gml:remarks>CRS for 2D pixel-domain referenced images.</gml:remarks>
  <gml:scope>Default CRS for 2D images that are referenced in the pixel domain.</gml:scope>
  <gml:CartesianCS gml:id="cartesian2D">
    <gml:identifier codeSpace="OGP">local/cs/OGC/0.1/Cartesian2D</gml:identifier>
    <gml:axis>
      <gml:CoordinateSystemAxis gml:id="i" uom="http://kahlua.eecs.jacobs-university.de:8080/def/uom/OGC/1.0/GridSpacing">
        <gml:identifier codeSpace="OGP">local/axis/OGC/0.1/i</gml:identifier>
        <gml:name>i</gml:name>
        <gml:axisAbbrev>i</gml:axisAbbrev>
        <gml:axisDirection codeSpace="OGP">horizontal</gml:axisDirection>
      </gml:CoordinateSystemAxis>
    </gml:axis>
    <gml:axis>
      <gml:CoordinateSystemAxis gml:id="j" uom="http://kahlua.eecs.jacobs-university.de:8080/def/uom/OGC/1.0/GridSpacing">
        <gml:identifier codeSpace="OGP">local/axis/OGC/0.1/j</gml:identifier>
        <gml:name>j</gml:name>
        <gml:axisAbbrev>j</gml:axisAbbrev>
        <gml:axisDirection codeSpace="EPSG">vertical</gml:axisDirection>
      </gml:CoordinateSystemAxis>
    </gml:axis>
  </gml:CartesianCS>
  <gml:ImageDatum gml:id="imageDatum">
    <gml:identifier codeSpace="OGP">local/datum/OGC/0.1/ImageDatumGridUpperLeft</gml:identifier>
    <gml:scope>A 2D image datum with the origin in the upper-left corner pixel of the grid.</gml:scope>
    <gml:pixelInCell codeSpace="OGP">local/pixelInCell/OGC/0.1/cellLowerBound</gml:pixelInCell>
  </gml:ImageDatum>
</gml:ImageCRS>