<?xml version="1.0" encoding="ISO-8859-1"?>
<identifiers at='/def' xmlns='http://www.opengis.net/crs-nts/1.0' xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmd="http://www.isotc211.org/2005/gmd">
  <identifier>/def/area</identifier>
  <identifier>/def/axis</identifier>
  <identifier>/def/axis-name</identifier>
  <identifier>/def/change-request</identifier>
  <identifier>/def/coordinateOperation</identifier>
  <identifier>/def/crs</identifier>
  <identifier>/def/cs</identifier>
  <identifier>/def/datum</identifier>
  <identifier>/def/deprecation</identifier>
  <identifier>/def/ellipsoid</identifier>
  <identifier>/def/meridian</identifier>
  <identifier>/def/method</identifier>
  <identifier>/def/naming-system</identifier>
  <identifier>/def/parameter</identifier>
  <identifier>/def/supersession</identifier>
  <identifier>/def/uom</identifier>
  <identifier>/def/version-history</identifier>
</identifiers>