// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package org.rasdaman.rasnet.message.internal;

public final class Internal {
  private Internal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InternalConnectRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rasnet.internal.InternalConnectRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code rasnet.internal.InternalConnectRequest}
   */
  public  static final class InternalConnectRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rasnet.internal.InternalConnectRequest)
      InternalConnectRequestOrBuilder {
    // Use InternalConnectRequest.newBuilder() to construct.
    private InternalConnectRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private InternalConnectRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InternalConnectRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalConnectRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalConnectRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest.class, org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rasnet.internal.InternalConnectRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rasnet.internal.InternalConnectRequest)
        org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalConnectRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalConnectRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest.class, org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest.Builder.class);
      }

      // Construct using org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalConnectRequest_descriptor;
      }

      public org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest getDefaultInstanceForType() {
        return org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest.getDefaultInstance();
      }

      public org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest build() {
        org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest buildPartial() {
        org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest result = new org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest) {
          return mergeFrom((org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest other) {
        if (other == org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rasnet.internal.InternalConnectRequest)
    }

    // @@protoc_insertion_point(class_scope:rasnet.internal.InternalConnectRequest)
    private static final org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest();
    }

    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<InternalConnectRequest>
        PARSER = new com.google.protobuf.AbstractParser<InternalConnectRequest>() {
      public InternalConnectRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new InternalConnectRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<InternalConnectRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InternalConnectRequest> getParserForType() {
      return PARSER;
    }

    public org.rasdaman.rasnet.message.internal.Internal.InternalConnectRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InternalConnectReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rasnet.internal.InternalConnectReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool success = 1;</code>
     */
    boolean hasSuccess();
    /**
     * <code>required bool success = 1;</code>
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code rasnet.internal.InternalConnectReply}
   */
  public  static final class InternalConnectReply extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rasnet.internal.InternalConnectReply)
      InternalConnectReplyOrBuilder {
    // Use InternalConnectReply.newBuilder() to construct.
    private InternalConnectReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private InternalConnectReply() {
      success_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InternalConnectReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              success_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalConnectReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalConnectReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply.class, org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply.Builder.class);
    }

    private int bitField0_;
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>required bool success = 1;</code>
     */
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, success_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rasnet.internal.InternalConnectReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rasnet.internal.InternalConnectReply)
        org.rasdaman.rasnet.message.internal.Internal.InternalConnectReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalConnectReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalConnectReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply.class, org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply.Builder.class);
      }

      // Construct using org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalConnectReply_descriptor;
      }

      public org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply getDefaultInstanceForType() {
        return org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply.getDefaultInstance();
      }

      public org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply build() {
        org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply buildPartial() {
        org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply result = new org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.success_ = success_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply) {
          return mergeFrom((org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply other) {
        if (other == org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply.getDefaultInstance()) return this;
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSuccess()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean success_ ;
      /**
       * <code>required bool success = 1;</code>
       */
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>required bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool success = 1;</code>
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        success_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rasnet.internal.InternalConnectReply)
    }

    // @@protoc_insertion_point(class_scope:rasnet.internal.InternalConnectReply)
    private static final org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply();
    }

    public static org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<InternalConnectReply>
        PARSER = new com.google.protobuf.AbstractParser<InternalConnectReply>() {
      public InternalConnectReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new InternalConnectReply(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<InternalConnectReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InternalConnectReply> getParserForType() {
      return PARSER;
    }

    public org.rasdaman.rasnet.message.internal.Internal.InternalConnectReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InternalDisconnectRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rasnet.internal.InternalDisconnectRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code rasnet.internal.InternalDisconnectRequest}
   */
  public  static final class InternalDisconnectRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rasnet.internal.InternalDisconnectRequest)
      InternalDisconnectRequestOrBuilder {
    // Use InternalDisconnectRequest.newBuilder() to construct.
    private InternalDisconnectRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private InternalDisconnectRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InternalDisconnectRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalDisconnectRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalDisconnectRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest.class, org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rasnet.internal.InternalDisconnectRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rasnet.internal.InternalDisconnectRequest)
        org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalDisconnectRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalDisconnectRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest.class, org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest.Builder.class);
      }

      // Construct using org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalDisconnectRequest_descriptor;
      }

      public org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest getDefaultInstanceForType() {
        return org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest.getDefaultInstance();
      }

      public org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest build() {
        org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest buildPartial() {
        org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest result = new org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest) {
          return mergeFrom((org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest other) {
        if (other == org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rasnet.internal.InternalDisconnectRequest)
    }

    // @@protoc_insertion_point(class_scope:rasnet.internal.InternalDisconnectRequest)
    private static final org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest();
    }

    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<InternalDisconnectRequest>
        PARSER = new com.google.protobuf.AbstractParser<InternalDisconnectRequest>() {
      public InternalDisconnectRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new InternalDisconnectRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<InternalDisconnectRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InternalDisconnectRequest> getParserForType() {
      return PARSER;
    }

    public org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InternalDisconnectReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rasnet.internal.InternalDisconnectReply)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code rasnet.internal.InternalDisconnectReply}
   */
  public  static final class InternalDisconnectReply extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rasnet.internal.InternalDisconnectReply)
      InternalDisconnectReplyOrBuilder {
    // Use InternalDisconnectReply.newBuilder() to construct.
    private InternalDisconnectReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private InternalDisconnectReply() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InternalDisconnectReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalDisconnectReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalDisconnectReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply.class, org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rasnet.internal.InternalDisconnectReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rasnet.internal.InternalDisconnectReply)
        org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalDisconnectReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalDisconnectReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply.class, org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply.Builder.class);
      }

      // Construct using org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_InternalDisconnectReply_descriptor;
      }

      public org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply getDefaultInstanceForType() {
        return org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply.getDefaultInstance();
      }

      public org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply build() {
        org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply buildPartial() {
        org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply result = new org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply) {
          return mergeFrom((org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply other) {
        if (other == org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rasnet.internal.InternalDisconnectReply)
    }

    // @@protoc_insertion_point(class_scope:rasnet.internal.InternalDisconnectReply)
    private static final org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply();
    }

    public static org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<InternalDisconnectReply>
        PARSER = new com.google.protobuf.AbstractParser<InternalDisconnectReply>() {
      public InternalDisconnectReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new InternalDisconnectReply(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<InternalDisconnectReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InternalDisconnectReply> getParserForType() {
      return PARSER;
    }

    public org.rasdaman.rasnet.message.internal.Internal.InternalDisconnectReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServiceRequestAvailableOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rasnet.internal.ServiceRequestAvailable)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code rasnet.internal.ServiceRequestAvailable}
   */
  public  static final class ServiceRequestAvailable extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rasnet.internal.ServiceRequestAvailable)
      ServiceRequestAvailableOrBuilder {
    // Use ServiceRequestAvailable.newBuilder() to construct.
    private ServiceRequestAvailable(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ServiceRequestAvailable() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceRequestAvailable(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_ServiceRequestAvailable_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_ServiceRequestAvailable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable.class, org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rasnet.internal.ServiceRequestAvailable}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rasnet.internal.ServiceRequestAvailable)
        org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_ServiceRequestAvailable_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_ServiceRequestAvailable_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable.class, org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable.Builder.class);
      }

      // Construct using org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_ServiceRequestAvailable_descriptor;
      }

      public org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable getDefaultInstanceForType() {
        return org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable.getDefaultInstance();
      }

      public org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable build() {
        org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable buildPartial() {
        org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable result = new org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable) {
          return mergeFrom((org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable other) {
        if (other == org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rasnet.internal.ServiceRequestAvailable)
    }

    // @@protoc_insertion_point(class_scope:rasnet.internal.ServiceRequestAvailable)
    private static final org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable();
    }

    public static org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ServiceRequestAvailable>
        PARSER = new com.google.protobuf.AbstractParser<ServiceRequestAvailable>() {
      public ServiceRequestAvailable parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ServiceRequestAvailable(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ServiceRequestAvailable> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceRequestAvailable> getParserForType() {
      return PARSER;
    }

    public org.rasdaman.rasnet.message.internal.Internal.ServiceRequestAvailable getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServiceResponseAvailableOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rasnet.internal.ServiceResponseAvailable)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code rasnet.internal.ServiceResponseAvailable}
   */
  public  static final class ServiceResponseAvailable extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:rasnet.internal.ServiceResponseAvailable)
      ServiceResponseAvailableOrBuilder {
    // Use ServiceResponseAvailable.newBuilder() to construct.
    private ServiceResponseAvailable(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ServiceResponseAvailable() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceResponseAvailable(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_ServiceResponseAvailable_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_ServiceResponseAvailable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable.class, org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rasnet.internal.ServiceResponseAvailable}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rasnet.internal.ServiceResponseAvailable)
        org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_ServiceResponseAvailable_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_ServiceResponseAvailable_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable.class, org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable.Builder.class);
      }

      // Construct using org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rasdaman.rasnet.message.internal.Internal.internal_static_rasnet_internal_ServiceResponseAvailable_descriptor;
      }

      public org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable getDefaultInstanceForType() {
        return org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable.getDefaultInstance();
      }

      public org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable build() {
        org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable buildPartial() {
        org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable result = new org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable) {
          return mergeFrom((org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable other) {
        if (other == org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:rasnet.internal.ServiceResponseAvailable)
    }

    // @@protoc_insertion_point(class_scope:rasnet.internal.ServiceResponseAvailable)
    private static final org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable();
    }

    public static org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ServiceResponseAvailable>
        PARSER = new com.google.protobuf.AbstractParser<ServiceResponseAvailable>() {
      public ServiceResponseAvailable parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ServiceResponseAvailable(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ServiceResponseAvailable> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceResponseAvailable> getParserForType() {
      return PARSER;
    }

    public org.rasdaman.rasnet.message.internal.Internal.ServiceResponseAvailable getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rasnet_internal_InternalConnectRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rasnet_internal_InternalConnectRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rasnet_internal_InternalConnectReply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rasnet_internal_InternalConnectReply_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rasnet_internal_InternalDisconnectRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rasnet_internal_InternalDisconnectRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rasnet_internal_InternalDisconnectReply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rasnet_internal_InternalDisconnectReply_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rasnet_internal_ServiceRequestAvailable_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rasnet_internal_ServiceRequestAvailable_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rasnet_internal_ServiceResponseAvailable_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rasnet_internal_ServiceResponseAvailable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016internal.proto\022\017rasnet.internal\"\030\n\026Int" +
      "ernalConnectRequest\"\'\n\024InternalConnectRe" +
      "ply\022\017\n\007success\030\001 \002(\010\"\033\n\031InternalDisconne" +
      "ctRequest\"\031\n\027InternalDisconnectReply\"\031\n\027" +
      "ServiceRequestAvailable\"\032\n\030ServiceRespon" +
      "seAvailableB&\n$org.rasdaman.rasnet.messa" +
      "ge.internal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_rasnet_internal_InternalConnectRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rasnet_internal_InternalConnectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rasnet_internal_InternalConnectRequest_descriptor,
        new java.lang.String[] { });
    internal_static_rasnet_internal_InternalConnectReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rasnet_internal_InternalConnectReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rasnet_internal_InternalConnectReply_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_rasnet_internal_InternalDisconnectRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_rasnet_internal_InternalDisconnectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rasnet_internal_InternalDisconnectRequest_descriptor,
        new java.lang.String[] { });
    internal_static_rasnet_internal_InternalDisconnectReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_rasnet_internal_InternalDisconnectReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rasnet_internal_InternalDisconnectReply_descriptor,
        new java.lang.String[] { });
    internal_static_rasnet_internal_ServiceRequestAvailable_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_rasnet_internal_ServiceRequestAvailable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rasnet_internal_ServiceRequestAvailable_descriptor,
        new java.lang.String[] { });
    internal_static_rasnet_internal_ServiceResponseAvailable_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_rasnet_internal_ServiceResponseAvailable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_rasnet_internal_ServiceResponseAvailable_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
