// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error.proto

package org.rasdaman.rasnet.service;

public final class Error {
  private Error() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ErrorMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.ErrorMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 error_no = 1;</code>
     */
    int getErrorNo();

    /**
     * <code>optional int32 kind = 2;</code>
     */
    int getKind();

    /**
     * <code>optional string error_text = 3;</code>
     */
    java.lang.String getErrorText();
    /**
     * <code>optional string error_text = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrorTextBytes();

    /**
     * <code>optional .common.ErrorMessage.ErrorMessageType type = 4;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .common.ErrorMessage.ErrorMessageType type = 4;</code>
     */
    org.rasdaman.rasnet.service.Error.ErrorMessage.ErrorMessageType getType();
  }
  /**
   * Protobuf type {@code common.ErrorMessage}
   */
  public  static final class ErrorMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common.ErrorMessage)
      ErrorMessageOrBuilder {
    // Use ErrorMessage.newBuilder() to construct.
    private ErrorMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ErrorMessage() {
      errorNo_ = 0;
      kind_ = 0;
      errorText_ = "";
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ErrorMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              errorNo_ = input.readUInt32();
              break;
            }
            case 16: {

              kind_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              errorText_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rasdaman.rasnet.service.Error.internal_static_common_ErrorMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rasdaman.rasnet.service.Error.internal_static_common_ErrorMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rasdaman.rasnet.service.Error.ErrorMessage.class, org.rasdaman.rasnet.service.Error.ErrorMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code common.ErrorMessage.ErrorMessageType}
     */
    public enum ErrorMessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>STL = 0;</code>
       */
      STL(0, 0),
      /**
       * <code>RERROR = 1;</code>
       */
      RERROR(1, 1),
      /**
       * <code>UNKNOWN = 2;</code>
       */
      UNKNOWN(2, 2),
      UNRECOGNIZED(-1, -1),
      ;

      /**
       * <code>STL = 0;</code>
       */
      public static final int STL_VALUE = 0;
      /**
       * <code>RERROR = 1;</code>
       */
      public static final int RERROR_VALUE = 1;
      /**
       * <code>UNKNOWN = 2;</code>
       */
      public static final int UNKNOWN_VALUE = 2;


      public final int getNumber() {
        if (index == -1) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      public static ErrorMessageType valueOf(int value) {
        switch (value) {
          case 0: return STL;
          case 1: return RERROR;
          case 2: return UNKNOWN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ErrorMessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ErrorMessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ErrorMessageType>() {
              public ErrorMessageType findValueByNumber(int number) {
                return ErrorMessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.rasdaman.rasnet.service.Error.ErrorMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final ErrorMessageType[] VALUES = values();

      public static ErrorMessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ErrorMessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:common.ErrorMessage.ErrorMessageType)
    }

    public static final int ERROR_NO_FIELD_NUMBER = 1;
    private int errorNo_;
    /**
     * <code>optional uint32 error_no = 1;</code>
     */
    public int getErrorNo() {
      return errorNo_;
    }

    public static final int KIND_FIELD_NUMBER = 2;
    private int kind_;
    /**
     * <code>optional int32 kind = 2;</code>
     */
    public int getKind() {
      return kind_;
    }

    public static final int ERROR_TEXT_FIELD_NUMBER = 3;
    private volatile java.lang.Object errorText_;
    /**
     * <code>optional string error_text = 3;</code>
     */
    public java.lang.String getErrorText() {
      java.lang.Object ref = errorText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorText_ = s;
        return s;
      }
    }
    /**
     * <code>optional string error_text = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorTextBytes() {
      java.lang.Object ref = errorText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>optional .common.ErrorMessage.ErrorMessageType type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .common.ErrorMessage.ErrorMessageType type = 4;</code>
     */
    public org.rasdaman.rasnet.service.Error.ErrorMessage.ErrorMessageType getType() {
      org.rasdaman.rasnet.service.Error.ErrorMessage.ErrorMessageType result = org.rasdaman.rasnet.service.Error.ErrorMessage.ErrorMessageType.valueOf(type_);
      return result == null ? org.rasdaman.rasnet.service.Error.ErrorMessage.ErrorMessageType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorNo_ != 0) {
        output.writeUInt32(1, errorNo_);
      }
      if (kind_ != 0) {
        output.writeInt32(2, kind_);
      }
      if (!getErrorTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, errorText_);
      }
      if (type_ != org.rasdaman.rasnet.service.Error.ErrorMessage.ErrorMessageType.STL.getNumber()) {
        output.writeEnum(4, type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorNo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, errorNo_);
      }
      if (kind_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, kind_);
      }
      if (!getErrorTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, errorText_);
      }
      if (type_ != org.rasdaman.rasnet.service.Error.ErrorMessage.ErrorMessageType.STL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.rasdaman.rasnet.service.Error.ErrorMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.service.Error.ErrorMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.service.Error.ErrorMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.rasdaman.rasnet.service.Error.ErrorMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.rasdaman.rasnet.service.Error.ErrorMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.service.Error.ErrorMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.service.Error.ErrorMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.rasdaman.rasnet.service.Error.ErrorMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.rasdaman.rasnet.service.Error.ErrorMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.rasdaman.rasnet.service.Error.ErrorMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.rasdaman.rasnet.service.Error.ErrorMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.ErrorMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.ErrorMessage)
        org.rasdaman.rasnet.service.Error.ErrorMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.rasdaman.rasnet.service.Error.internal_static_common_ErrorMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.rasdaman.rasnet.service.Error.internal_static_common_ErrorMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.rasdaman.rasnet.service.Error.ErrorMessage.class, org.rasdaman.rasnet.service.Error.ErrorMessage.Builder.class);
      }

      // Construct using org.rasdaman.rasnet.service.Error.ErrorMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        errorNo_ = 0;

        kind_ = 0;

        errorText_ = "";

        type_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.rasdaman.rasnet.service.Error.internal_static_common_ErrorMessage_descriptor;
      }

      public org.rasdaman.rasnet.service.Error.ErrorMessage getDefaultInstanceForType() {
        return org.rasdaman.rasnet.service.Error.ErrorMessage.getDefaultInstance();
      }

      public org.rasdaman.rasnet.service.Error.ErrorMessage build() {
        org.rasdaman.rasnet.service.Error.ErrorMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.rasdaman.rasnet.service.Error.ErrorMessage buildPartial() {
        org.rasdaman.rasnet.service.Error.ErrorMessage result = new org.rasdaman.rasnet.service.Error.ErrorMessage(this);
        result.errorNo_ = errorNo_;
        result.kind_ = kind_;
        result.errorText_ = errorText_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.rasdaman.rasnet.service.Error.ErrorMessage) {
          return mergeFrom((org.rasdaman.rasnet.service.Error.ErrorMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.rasdaman.rasnet.service.Error.ErrorMessage other) {
        if (other == org.rasdaman.rasnet.service.Error.ErrorMessage.getDefaultInstance()) return this;
        if (other.getErrorNo() != 0) {
          setErrorNo(other.getErrorNo());
        }
        if (other.getKind() != 0) {
          setKind(other.getKind());
        }
        if (!other.getErrorText().isEmpty()) {
          errorText_ = other.errorText_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.rasdaman.rasnet.service.Error.ErrorMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.rasdaman.rasnet.service.Error.ErrorMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int errorNo_ ;
      /**
       * <code>optional uint32 error_no = 1;</code>
       */
      public int getErrorNo() {
        return errorNo_;
      }
      /**
       * <code>optional uint32 error_no = 1;</code>
       */
      public Builder setErrorNo(int value) {

        errorNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 error_no = 1;</code>
       */
      public Builder clearErrorNo() {

        errorNo_ = 0;
        onChanged();
        return this;
      }

      private int kind_ ;
      /**
       * <code>optional int32 kind = 2;</code>
       */
      public int getKind() {
        return kind_;
      }
      /**
       * <code>optional int32 kind = 2;</code>
       */
      public Builder setKind(int value) {

        kind_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 kind = 2;</code>
       */
      public Builder clearKind() {

        kind_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errorText_ = "";
      /**
       * <code>optional string error_text = 3;</code>
       */
      public java.lang.String getErrorText() {
        java.lang.Object ref = errorText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error_text = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrorTextBytes() {
        java.lang.Object ref = errorText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error_text = 3;</code>
       */
      public Builder setErrorText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        errorText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_text = 3;</code>
       */
      public Builder clearErrorText() {

        errorText_ = getDefaultInstance().getErrorText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_text = 3;</code>
       */
      public Builder setErrorTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        errorText_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .common.ErrorMessage.ErrorMessageType type = 4;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .common.ErrorMessage.ErrorMessageType type = 4;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .common.ErrorMessage.ErrorMessageType type = 4;</code>
       */
      public org.rasdaman.rasnet.service.Error.ErrorMessage.ErrorMessageType getType() {
        org.rasdaman.rasnet.service.Error.ErrorMessage.ErrorMessageType result = org.rasdaman.rasnet.service.Error.ErrorMessage.ErrorMessageType.valueOf(type_);
        return result == null ? org.rasdaman.rasnet.service.Error.ErrorMessage.ErrorMessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .common.ErrorMessage.ErrorMessageType type = 4;</code>
       */
      public Builder setType(org.rasdaman.rasnet.service.Error.ErrorMessage.ErrorMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .common.ErrorMessage.ErrorMessageType type = 4;</code>
       */
      public Builder clearType() {

        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:common.ErrorMessage)
    }

    // @@protoc_insertion_point(class_scope:common.ErrorMessage)
    private static final org.rasdaman.rasnet.service.Error.ErrorMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.rasdaman.rasnet.service.Error.ErrorMessage();
    }

    public static org.rasdaman.rasnet.service.Error.ErrorMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ErrorMessage>
        PARSER = new com.google.protobuf.AbstractParser<ErrorMessage>() {
      public ErrorMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ErrorMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ErrorMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorMessage> getParserForType() {
      return PARSER;
    }

    public org.rasdaman.rasnet.service.Error.ErrorMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_ErrorMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_ErrorMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013error.proto\022\006common\"\255\001\n\014ErrorMessage\022\020" +
      "\n\010error_no\030\001 \001(\r\022\014\n\004kind\030\002 \001(\005\022\022\n\nerror_" +
      "text\030\003 \001(\t\0223\n\004type\030\004 \001(\0162%.common.ErrorM" +
      "essage.ErrorMessageType\"4\n\020ErrorMessageT" +
      "ype\022\007\n\003STL\020\000\022\n\n\006RERROR\020\001\022\013\n\007UNKNOWN\020\002B#\n" +
      "\033org.rasdaman.rasnet.service\200\001\000\210\001\000b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_common_ErrorMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_ErrorMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_ErrorMessage_descriptor,
        new java.lang.String[] { "ErrorNo", "Kind", "ErrorText", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
