# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common_service.proto',
  package='rasnet.service',
  #syntax='proto3'
  serialized_pb=_b('\n\x14\x63ommon_service.proto\x12\x0erasnet.service\"\x06\n\x04VoidB\x1d\n\x1borg.rasdaman.rasnet.serviceb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='rasnet.service.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  #syntax='proto3'
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=46,
)

DESCRIPTOR.message_types_by_name['Void'] = _VOID

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'common_service_pb2'
  # @@protoc_insertion_point(class_scope:rasnet.service.Void)
  ))
_sym_db.RegisterMessage(Void)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033org.rasdaman.rasnet.service'))
import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
